name: Create Heroku environment for feature branch

on:
  push:
    branches:
      - setup-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: feature-${{ github.ref_name }}
